# Generated by Django 4.1.2 on 2022-10-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItemn',
            new_name='OrderItem',
        ),
    ]
